- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copying the mongo repo
    copy: 
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
  - name: installing mongodb server
    package:
     name: mongodb-org
     state: present