- name: installing catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs 20
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    package:
     name: nodejs
     state: present
  - name: roboshop system user creation
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop System user"