- name: installing user server
  hosts: user
  tasks: 
  - name: enabling nodejs 20
    command: dnf module enable nodejs:20 -y
  - name: installing nodejs   
    package: 
      name: nodejs
      state: present
  - name: creating user 
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop System user"
  - name: deleting dir app
    file:
     path: /app
     state: absent
  - name: deleting catalogue.zip in tmp directory  
    file:
     path: /tmp/user.zip
     state: absent
  - name: create directory
    file:
     path: /app
     state: present

  - name: downloading app code
    get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
     dest: /tmp/user.zip

  - name: unzip for catalogue user
    unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes
  - name: install dependencies
    community.general.npm:
      path: /app
  - name: copy user service
    template: 
    src: user.service.j2
    dest: /etc/systemd/system/user.service
  -  name: deamon reload
     systemd_service:
      name: user
      daemon_reload: true
  - name: enable and restart user
    service:
      name: user
      state: restarted
      enabled: yes


  