[local]
localhost

; [mongodb]
; mongodb.srikanth865.online

; [redis]
; redis.srikanth865.online


; [mysql]
; mysql.srikanth865.online


; [rabbitmq]
; rabbitmq.srikanth865.online


; [catalogue]
; catalogue.srikanth865.online

; [user]
; user.daws90s.shop

; [cart]
; cart.daws90s.shop

; [shipping]
; shipping.daws90s.shop

; [payment]
; payment.daws90s.shop

; [frontend]
; frontend.daws90s.shop    