[local]
localhost

[mongodb]
172.31.10.132

[redis]
redis.srikanth865.online


[mysql]
mysql.dsrikanth865.online


[rabbitmq]
rabbitmq.srikanth865.online


[catalogue]
catalogue.daws90s.shop

[user]
user.daws90s.shop

[cart]
cart.daws90s.shop

[shipping]
shipping.daws90s.shop

[payment]
payment.daws90s.shop

[frontend]
frontend.daws90s.shop