- name: configuring mongodb server
  hosts: mongodb
  become: yes

  tasks:
    - name: Test
      debug:
        msg: "MongoDB Server"
        register: output
        debug:
           msg: "{{ output }}"